version: '3.8'

services:
  webserver:
    build: .
    ports:
      - "5000:5000"
    container_name: python-webserver
    restart: unless-stopped
    volumes:
      - ./app:/app
      - ./receipt.odt:/app/receipt.odt
